import:
    add_to_inbox: true
    skip_existing_galleries: true
    transparent_nested_folders: true
server:
  server_name: hpxl
  host: 0.0.0.0
  port: 7007
  host_web: 0.0.0.0
  port_web: 7008
  disable_default_user: false
  require_auth: true
  allow_guests: false
watch:
    enable: true
    dirs:
      - ${HPX_CONTENT}
    options:
      ${HPX_CONTENT}:
        import.scan_on_startup: true
plugin:
    plugin_dir: ${HPX_DATA}/plugins
#db:
#    dialect: postgres
#    username: happypandax
#    password: postgres
#    host: db
#    port: 5432
#    name: happypanda